/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.46.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as ai from "../ai.js";
import type * as aiLlm from "../aiLlm.js";
import type * as aiPrompt from "../aiPrompt.js";
import type * as aiRecommendation from "../aiRecommendation.js";
import type * as aiTools from "../aiTools.js";
import type * as clubs from "../clubs.js";
import type * as coaches from "../coaches.js";
import type * as demo from "../demo.js";
import type * as invites from "../invites.js";
import type * as lib_auth from "../lib/auth.js";
import type * as matchEvents from "../matchEvents.js";
import type * as matches from "../matches.js";
import type * as opponents from "../opponents.js";
import type * as players from "../players.js";
import type * as teams from "../teams.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  ai: typeof ai;
  aiLlm: typeof aiLlm;
  aiPrompt: typeof aiPrompt;
  aiRecommendation: typeof aiRecommendation;
  aiTools: typeof aiTools;
  clubs: typeof clubs;
  coaches: typeof coaches;
  demo: typeof demo;
  invites: typeof invites;
  "lib/auth": typeof lib_auth;
  matchEvents: typeof matchEvents;
  matches: typeof matches;
  opponents: typeof opponents;
  players: typeof players;
  teams: typeof teams;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
